# Generated by Django 2.0.5 on 2018-07-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
